services:
  api:
    build: .
    container_name: "app-myfinances-api"
    restart: unless-stopped
    env_file: ".env.${NODE_ENV}"
    environment:
      - DB_HOST=app-myfinances-db
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - myfinances_net

  db:
    image: postgres:16
    container_name: "app-myfinances-db"
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ".env.${NODE_ENV}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - myfinances_net

networks:
  myfinances_net:
