services:
  api:
    build: .
    container_name: "${APP_NAME}-api"
    restart: unless-stopped
    env_file: ".env.${NODE_ENV}"
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - myfinances_net

  db:
    image: postgres:16
    container_name: "${APP_NAME}-db"
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ".env.${NODE_ENV}"
    volumes:
      - myfinances_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - myfinances_net

volumes:
  myfinances_db_data:

networks:
  myfinances_net:
